name: 🐳 Build, Test & Publish Fortune-Cowsay-API

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build-and-test:
    name: 🧱 Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        run: docker build -t fortune-cowsay-api:test .

      - name: Run container & healthcheck
        run: |
          docker run -d --rm -p 8080:8080 --name fortune-api-test fortune-cowsay-api:test
          echo "Waiting for API..."
          for i in {1..10}; do
            if curl -fs http://localhost:8080/api/health >/dev/null 2>&1; then
              echo "✅ API healthy!"
              docker rm -f fortune-api-test >/dev/null 2>&1 || true
              exit 0
            fi
            sleep 3
          done
          echo "❌ API healthcheck failed"
          docker logs fortune-api-test || true
          docker rm -f fortune-api-test >/dev/null 2>&1 || true
          exit 1

  multiarch-push:
    name: 🚀 Build & Push (multi-arch)
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ewald1976/fortune-cowsay-api:latest
            ewald1976/fortune-cowsay-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-dockerhub-readme:
    name: 🐮 Update DockerHub Overview
    needs: [multiarch-push]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync README to DockerHub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ewald1976/fortune-cowsay-api
          readme-filepath: ./README.md
