version: "3.9"

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: php-fpm
    volumes:
      - ./lumen-app:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "8080:8080"
    depends_on:
      - php-fpm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
